# Обзор библиотеки numpy

## Общие сведения

Numpy (numeric python) - библиотека с набором пре-компилированных математических функций. Как правило, numpy импортируется в пространство имен np.

In [2]:
import numpy as np

Основой numpy являются массивы данных. Они могут быть как одномерными, так и многомерными:

In [50]:
a = np.array([1,2,3,4], float)
a

array([1., 2., 3., 4.])

In [51]:
b = np.array([5.,6.,7.,8.])
b

array([5., 6., 7., 8.])

In [52]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

При создании массива тип данных может быть указан в явном виде (как в случае с массивом a)

Размер массива определяется с помощью параметра shape:

In [70]:
c.shape

(2, 3)

## Основные функции

#### Нарезка

Массивы поддерживают т.н. "нарезку" (slicing) по индексам:

In [24]:
a[0]

1.0

In [31]:
c[1]

array([4, 5, 6])

In [32]:
c[-1:,-2:]

array([[5, 6]])

In [29]:
c[:,1:]

array([[2, 3],
       [5, 6]])

#### Определение длины массива

Для определения длины массива используется функция len (в случае многомерных массивов она вовзвращает длину массива по первому измерению):

In [33]:
len(c), len(c[0])

(2, 3)

#### Поиск

Массивы поддерживают возможность поиска символа внутри при помощи in:

In [34]:
2 in a

True

In [35]:
22 in a

False

#### Преобразования массивов

Массивы можно склеивать (concatenate):

In [100]:
d = np.concatenate((a,b))
d

array([1., 2., 3., 4., 5., 6., 7., 8.])

По умолчанию, слияние выполняется по первому измерению, но может быть переопределено с помощью параметра axis:

In [57]:
e = np.array([[1,2], [3,4]])
f = np.array([[5,6], [7,8]])

In [72]:
g = np.concatenate((e,f), axis=0)
g

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
h = np.concatenate((e,f), axis=1)
h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

... транспонировать:

In [78]:
h.transpose()

array([[1, 3],
       [2, 4],
       [5, 7],
       [6, 8]])

... заполнять заданными значениями:

In [83]:
g.fill(9)
g

array([[9, 9],
       [9, 9],
       [9, 9],
       [9, 9]])

... преобразовывать в списки:

In [87]:
h.tolist()

[[1, 2, 5, 6], [3, 4, 7, 8]]

... делать плоскими:

In [88]:
h.flatten()

array([1, 2, 5, 6, 3, 4, 7, 8])

... или преобразовывать в нужную форму:

In [91]:
d.reshape(4,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

<b>Важно:</b> при любых преобхованиях формы массива следует помнить, что массив в numpy - это мета-данные (определяют только тип и форму) и ссылка на сами данные. Поэтому преобразования создают новые мета-данные, но не копируют данные:

In [101]:
d

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [102]:
i = d.reshape(4,2)
i

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [103]:
i[2,:] = 0
i

array([[1., 2.],
       [3., 4.],
       [0., 0.],
       [7., 8.]])

In [104]:
d

array([1., 2., 3., 4., 0., 0., 7., 8.])

Таким образом на массивах сказывается стандартное связывание имен в Python. При необходимости создания полной копии массива используется одноименная функция:

In [107]:
j = np.copy(i)
j

array([[1., 2.],
       [3., 4.],
       [0., 0.],
       [7., 8.]])

In [109]:
i[2,:].fill(9)
i

array([[1., 2.],
       [3., 4.],
       [9., 9.],
       [7., 8.]])

In [110]:
j

array([[1., 2.],
       [3., 4.],
       [0., 0.],
       [7., 8.]])

Иногда может быть полезной функция созданию дополнительного уровня массива. Выполняется эта операция с помощью метода newaxis:

In [113]:
j[np.newaxis,:]

array([[[1., 2.],
        [3., 4.],
        [0., 0.],
        [7., 8.]]])

## Источники:

1. <a href='http://www.numpy.org/'>Официальный сайт</a>
2. <a href='https://habr.com/post/352678/'>Цикл статей "NumPy в Python" на habr.com</a>